### ISSUE TITLE
Cosas para hacer

### ISSUE THREAD

**Issue by fedekau** [fedekau/tweets-clustering#1]
# TODO
## Limpiar
- [ ] Tweets (@fedekau)
  - [x] Tokenización
  - [x] Eliminar stopwords
  - [x] Eliminar puntuación
  - [x] Sacar `...`
  - [x] Sacar `jaja, jeje, jajja, jijij, etc..`
  - [x] Eliminar emoticones (@flarra)
  - [x] Eliminar links (Usar metadata de url)
  - [x] Método con `#` ( Sacarlo de `data.entities.hashtags`)
  - [x] Método con `@`
  - [ ] Reduccion de letras repetidas? (`ggggoooooolll`)
  - [ ] `5-1` no se está sacando, dejar tokens que sean solo letras? (procesarlo al final)
  - [ ] Eliminar fechas/horas. Ejemplo `14h`
## Definir distancia

Definir formalmente `distancia(Tweet, Tweet)`
- [ ] En base a persona
- [ ] En base a topico
- [ ] Ambos
## Código
- [ ] Ver tema rutas relativas 
- [ ] Implementar Bag of words básico.
- [x] Crear contador de tweets en `Person` (@FLarra)
  - [x] Saltear aquellos con contadores mas altos (a 100)
  - [x] Por dar fecha de cuando arrancar pa atras! (o a partir del tweet mas viejo ~)
- [ ] Traer Tweets que publican las entidades(origen cuenta de tweets oficiales)
- [ ] arreglar las busqudas por: #Luis Suarez por ejemplo
## Documentos
- [x] Estado del arte
- [x] Pasar a LaTeX (overleaf) 
## Estudiar
- Bag of words (@fedekau @FLarra)
- Embeddings
- Wor2Vec
- TensorFlow
## Extras
- [x] Mandar mail el jueves (6 de octubre) para juntarse proxima semana
